var searchData=
[
  ['race_9580',['Race',['../structRace.html',1,'']]],
  ['ram_5fdspace_9581',['ram_dspace',['../structram__dspace.html',1,'']]],
  ['ram_5fdspace_5flist_9582',['ram_dspace_list',['../structram__dspace__list.html',1,'']]],
  ['ram_5fdspace_5fwaiter_9583',['ram_dspace_waiter',['../structram__dspace__waiter.html',1,'']]],
  ['rb_5fbuffer_9584',['rb_buffer',['../structrb__buffer.html',1,'']]],
  ['refos_5fio_5finternal_5fstate_9585',['refos_io_internal_state',['../structrefos__io__internal__state.html',1,'']]],
  ['refos_5fio_5fmmap_5fsegment_5fstate_9586',['refos_io_mmap_segment_state',['../structrefos__io__mmap__segment__state.html',1,'']]],
  ['region_9587',['region',['../structregion.html',1,'']]],
  ['rgb_9588',['RGB',['../structRGB.html',1,'']]],
  ['rm_9589',['rm',['../structrm.html',1,'']]],
  ['role_9590',['Role',['../structRole.html',1,'']]],
  ['roleadvance_9591',['RoleAdvance',['../structRoleAdvance.html',1,'']]],
  ['rolename_9592',['RoleName',['../structRoleName.html',1,'']]],
  ['room_5fdoor_9593',['room_door',['../structroom__door.html',1,'']]],
  ['rpc_5fbuffer_5fs_9594',['rpc_buffer_s',['../structrpc__buffer__s.html',1,'']]],
  ['rpc_5fclient_5fstate_5fs_9595',['rpc_client_state_s',['../structrpc__client__state__s.html',1,'']]]
];
