var searchData=
[
  ['race_9578',['Race',['../structRace.html',1,'']]],
  ['ram_5fdspace_9579',['ram_dspace',['../structram__dspace.html',1,'']]],
  ['ram_5fdspace_5flist_9580',['ram_dspace_list',['../structram__dspace__list.html',1,'']]],
  ['ram_5fdspace_5fwaiter_9581',['ram_dspace_waiter',['../structram__dspace__waiter.html',1,'']]],
  ['rb_5fbuffer_9582',['rb_buffer',['../structrb__buffer.html',1,'']]],
  ['refos_5fio_5finternal_5fstate_9583',['refos_io_internal_state',['../structrefos__io__internal__state.html',1,'']]],
  ['refos_5fio_5fmmap_5fsegment_5fstate_9584',['refos_io_mmap_segment_state',['../structrefos__io__mmap__segment__state.html',1,'']]],
  ['region_9585',['region',['../structregion.html',1,'']]],
  ['rgb_9586',['RGB',['../structRGB.html',1,'']]],
  ['rm_9587',['rm',['../structrm.html',1,'']]],
  ['role_9588',['Role',['../structRole.html',1,'']]],
  ['roleadvance_9589',['RoleAdvance',['../structRoleAdvance.html',1,'']]],
  ['rolename_9590',['RoleName',['../structRoleName.html',1,'']]],
  ['room_5fdoor_9591',['room_door',['../structroom__door.html',1,'']]],
  ['rpc_5fbuffer_5fs_9592',['rpc_buffer_s',['../structrpc__buffer__s.html',1,'']]],
  ['rpc_5fclient_5fstate_5fs_9593',['rpc_client_state_s',['../structrpc__client__state__s.html',1,'']]]
];
